.\" syntorxgen.5, Boone, 07/20/02
.\" Documentation for the syntorxgen program input files
.\" Copyright (C) 2002, Dennis Boone, East Lansing, MI
.\"
.\" Modifications:
.\" 07/20/02 Boone      Initial coding
.\" End Modifications
.TH syntorxgen 5 "July 2002" Linux "User Manuals"
.SH NAME
syntorxgen \- Input file format for syntorxgen
.SH DESCRIPTION

.SH AUTHOR
Dennis Boone <jm-sxg at yagi.h-net.msu.edu>
.SH "SEE ALSO"
.BR syntorxgen (1)
