#!/usr/bin/perl
# genplfloattest, Boone, 02/13/05
# Generate a syntorxgen input file to test for floating point rounding errors
# Copyright (C) 2005, Dennis Boone, East Lansing, MI
#
# Modifications:
# 02/13/05 Boone      Initial coding
# End Modifications
#
# Syntorxgen is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published
# by the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# Syntorxgen is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with syntorxgen; if not, write to the Free Software Foundation,
# Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

	@pls =
	(
		67.0, 69.3, 71.9, 74.4, 77.0, 79.7, 82.5, 85.4, 88.5, 91.5,
		94.8, 97.4, 100.0, 103.5, 107.2, 110.9, 114.8, 118.8, 123.0,
		127.3, 131.8, 136.5, 141.3, 146.2, 151.4, 156.7, 162.2, 167.9,
		173.8, 179.9, 186.2, 192.8, 203.5, 206.5, 210.7, 218.1, 225.7,
		229.1, 233.6, 241.8, 250.3, 254.1
	);

	print "nmodes 42;\n";
	for ($i = 0; $i < 42; $i++)
	{
		print "mode ", $i+1, "\n",
			"{\n",
			"\ttxfreq 145.000;\n",
			"\ttxpl ", sprintf("%4.1f", $pls[$i]), ";\n",
			"};\n";
	}
